name: "Build AUR Packages and Upload"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-aur:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build AUR packages in Arch Linux container
        run: |
          docker run --rm -v "$PWD:/work" -w /work \
            archlinux:base-devel bash -c "
              pacman -Syu --noconfirm
              pacman -S --noconfirm git sudo fakeroot curl
              useradd -m builder
              echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
              chown -R builder /work
              su builder -c '
                cd aur/ectool && makepkg -sf --noconfirm && mv *.pkg.tar.zst /work
                cd ../cbmem && makepkg -sf --noconfirm && mv *.pkg.tar.zst /work
              '
            "

      - name: Upload AUR packages to GitHub Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: chromium-tools
          name: "chromium-tools"
          draft: true
          prerelease: false
          files: |
            *.pkg.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
