name: "Release Packages"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev fakeroot

      - name: Build .deb packages
        run: |
          cd deb
          mkdir -p chromium-ectool/usr/bin
          mkdir -p chromium-cbmem/usr/bin
          curl -L https://files.tree123.org/utils/x86_64/gnu/ectool -o chromium-ectool/usr/bin/ectool
          curl -L https://files.tree123.org/utils/x86_64/gnu/cbmem -o chromium-cbmem/usr/bin/cbmem
          chmod a+x chromium-ectool/usr/bin/ectool
          chmod a+x chromium-cbmem/usr/bin/cbmem
          dpkg-deb --build chromium-ectool
          dpkg-deb --build chromium-cbmem
          mv chromium-ectool.deb ../chromium-ectool.deb
          mv chromium-cbmem.deb ../chromium-cbmem.deb

      - name: Build AUR packages in Arch Linux container
        run: |
          docker run --rm -v "$PWD:/work" -w /work \
            archlinux:base-devel bash -c "
              pacman -Syu --noconfirm
              pacman -S --noconfirm git sudo fakeroot curl
              useradd -m builder
              echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
              chown -R builder /work
              su builder -c '
                cd aur/ectool && makepkg -sf --noconfirm && mv *.pkg.tar.zst /work
                cd ../cbmem && makepkg -sf --noconfirm && mv *.pkg.tar.zst /work
              '
            "

      - name: Create or update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: chromium-tools
          name: "chromium-tools"
          draft: false
          prerelease: false
          files: |
            chromium-ectool.deb
            chromium-cbmem.deb
            *.pkg.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
